// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqjdwkjltflgczcczcyc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxamR3a2psdGZsZ2N6Y2N6Y3ljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMzE1MzAsImV4cCI6MjA3MDgwNzUzMH0.hJwwXDQQa4Apf-nZllgNCnpLvIhg_7EdIFJyGP7Axik";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});